src/Entity/Offre.php
<?php

namespace App\Entity;

use App\Repository\OffreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OffreRepository::class)]
class Offre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nomEntreprise = null;

    #[ORM\Column(length: 255)]
    private ?string $nomOffre = null;

    #[ORM\Column(length: 255)]
    private ?string $Description = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(length: 100)]
    private ?string $telephone = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateDebut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateLimite = null;

    #[ORM\ManyToOne(targetEntity: TypeOffre::class, cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: true,)]
    private ?TypeOffre $fk_typeOffre = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $dateCreate = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomEntreprise(): ?string
    {
        return $this->nomEntreprise;
    }

    public function setNomEntreprise(string $nomEntreprise): static
    {
        $this->nomEntreprise = $nomEntreprise;

        return $this;
    }

    public function getNomOffre(): ?string
    {
        return $this->nomOffre;
    }

    public function setNomOffre(string $nomOffre): static
    {
        $this->nomOffre = $nomOffre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->dateDebut;
    }

    public function setDateDebut(\DateTimeInterface $dateDebut): static
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    public function getDateLimite(): ?\DateTimeInterface
    {
        return $this->dateLimite;
    }

    public function setDateLimite(\DateTimeInterface $dateLimite): static
    {
        $this->dateLimite = $dateLimite;

        return $this;
    }

    public function getFkTypeOffre(): ?TypeOffre
    {
        return $this->fk_typeOffre;
    }

    public function setFkTypeOffre(TypeOffre $fk_typeOffre): static
    {
        $this->fk_typeOffre = $fk_typeOffre;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getDateCreate(): ?\DateTimeInterface
    {
        return $this->dateCreate;
    }

    public function setDateCreate(?\DateTimeInterface $dateCreate): static
    {
        $this->dateCreate = $dateCreate;

        return $this;
    }


}

src/Controller/EntrepriseController.php
<?php

namespace App\Controller;

use App\Entity\Entreprise;
use App\Entity\Offre;
use App\Repository\EntrepriseRepository;
use App\Repository\OffreRepository;
use App\Repository\TypeOffreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
#[Route("/entreprise")]
class EntrepriseController extends AbstractController
{
    #[Route('/', name: 'app_entreprise')]
    public function index(): Response
    {

        return $this->render('entreprise/index.html.twig');
    }


    #[Route('/soumettre', name: 'app_soumettre')]
    public function put(Request $request, EntityManagerInterface $entityManager, TypeOffreRepository $typeOffreRepository): Response
    {
        $typeOffres = $typeOffreRepository->findAll();
        try {
            if ($request->isMethod('POST')) {
            // Récupérez les données du formulaire
            $entreprise = new Entreprise();
            $nom = $request->request->get('nom');
            $email = $request->request->get('email');
            $telephone = $request->request->get('telephone');
            $offreId = $request->request->get('typeOffre');
            $nomEntreprise = $request->request->get('nomEntreprise');
            $description = $request->request->get('description');
            $dateCloture = $request->request->get('dateCloture');
            $tailleEntreprise = $request->request->get('taille');
            $prenom = $request->request->get('prenom');
            $secteurActivite = $request->request->get('secteur');
            $localisation = $request->request->get('lieu');
            $experienceRequise = $request->request->get('experience');
            $competencesRequises = $request->request->get('competence');
            $dateCreation = $request->request->get('dateDepot');

            $mailResponsable = $request->request->get('mail');
            $telResponsable = $request->request->get('tel');
            $niveau = $request->request->get('niveau');
            $domainRecherche = $request->request->get('domaine');
            $dateEnvoi = new \DateTime('now');

            // Validate and convert date fields
            try {
                $dateCloture = new \DateTime($dateCloture);
            } catch (\Exception $e) {
                return new Response('Invalid date format for dateCloture', Response::HTTP_BAD_REQUEST);
            }

            try {
                $dateCreation = new \DateTime($dateCreation);
            } catch (\Exception $e) {
                return new Response('Invalid date format for dateCreation', Response::HTTP_BAD_REQUEST);
            }

            // Retrieve the TypeOffre entity
            $tOffre = $typeOffreRepository->findOneBy(['id' => $offreId]);
            if (!$tOffre) {
                return new Response('Invalid typeOffre', Response::HTTP_BAD_REQUEST);
            }

            // Set the Entreprise entity properties
            $entreprise->setNom($nom);
            $entreprise->setPrenom($prenom);
            $entreprise->setEmail($email);
            $entreprise->setNomEntreprise($nomEntreprise);
            $entreprise->setTelephone($telephone);
            $entreprise->addFkTypeOffre($tOffre);
            $entreprise->setDateLimite($dateCloture);
            $entreprise->setDescription($description);
            $entreprise->setTaille($tailleEntreprise);
            $entreprise->setDomaine($secteurActivite);
            $entreprise->setLieu($localisation);
            $entreprise->setExperience($experienceRequise);
            $entreprise->setCompetence($competencesRequises);
            $entreprise->setDateCreation($dateCreation);
            $entreprise->setEmailResponsable($mailResponsable);
            $entreprise->setTelResponsable($telResponsable);
            $entreprise->setNiveauRecherche($niveau);
            $entreprise->setDomaineRecherche($domainRecherche);
            $entreprise->setDateEnvoi($dateEnvoi);
            $entreprise->setStatut(false);


            // Persist the entity to the database
            $entityManager->persist($entreprise);
            $entityManager->flush();
            $this->addFlash(
               'success',
               'Votre offre à été soumis avec succès ! '
            );
            return $this->redirectToRoute('app_entreprise');
        }
        } catch (\Exception $e) {
            $this->addFlash(
               'danger',
               'Votre formulaire n\'a pas été soumise !'
            );
            return $this->redirectToRoute('app_entreprise');
        }


        return $this->render('entreprise/soumettre.html.twig', [
            'typeOffres' => $typeOffres,
        ]);
    }

    #[Route('/offre', name: 'app_offreEntreprise')]
    public function index2( EntrepriseRepository $entrepriseRepository, TypeOffreRepository $typeOffreRepository, OffreRepository $offreRepository): Response
    {
        $offreEntreprise = $entrepriseRepository->findAll();
        $offrePublie = $offreRepository->findAll();
        $context = ['offre_entreprises'=> $offreEntreprise,
        'offre_publies'=> $offrePublie,
        'typeOffres' => $typeOffreRepository->findAll(),
    ];

        return $this->render('entreprise/gestion_offre.html.twig', $context);
    }

    #[Route('/{id}', name: 'app_showEntreprise')]
    public function show(Entreprise $offreEntreprise ): Response
    {
        $context = ['offre_entreprise'=> $offreEntreprise];

        return $this->render('entreprise/show.html.twig', $context);
    }
    #[Route('/publier/{id}', name: 'app_publier')]
    public function postule(Entreprise $offreEntreprise, Request $request, EntityManagerInterface $entityManager): Response
    {
        try {
            // Vérifiez si le statut de l'offre est déjà publié
        if ($offreEntreprise->isStatut() === true) {
            $this->addFlash('warning', 'Cette offre a déjà été publiée.');
            return $this->redirectToRoute('app_offreEntreprise');
        }
            $toffre = $offreEntreprise->getFkTypeOffre();

            $offre = new Offre();
            $offre->setNomEntreprise($offreEntreprise->getNomEntreprise());
            $offre->setDescription($offreEntreprise->getDescription());
            $offre->setEmail($offreEntreprise->getEmail());
            $offre->setTelephone($offreEntreprise->getTelephone());
            $offre->setDateDebut($offreEntreprise->getDateCreation());
            $offre->setDateLimite($offreEntreprise->getDateLimite());

            // Si vous avez une seule relation avec un type d'offre, vous pouvez l'ajouter directement
            if ($toffre !== null && !$toffre->isEmpty()) {
                $offre->setFkTypeOffre($toffre->first());
            }
    $offre->setNomOffre($toffre->first()->getNom());
            $offre->setImage(""); 
            $offre->setDateCreate(new \DateTime('now')); 
            $offreEntreprise->setStatut(true);


            // Enregistrement de l'offre dans la base de données
            $entityManager->persist($offre);
            $entityManager->flush();

            // Message flash pour indiquer que l'opération s'est bien déroulée
            $this->addFlash('success', 'Offre ajoutée avec succès.');
        } catch (\Exception $e) {
            // En cas d'erreur, ajoutez un message flash d'erreur
            $this->addFlash('error', 'Une erreur est survenue lors de l\'ajout de l\'offre.');
        }

        // Redirection vers une page appropriée
        return $this->redirectToRoute('app_offreEntreprise');
    }

}

templates/entreprise/_partials/_contact.html.twig
 <div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s" id="contact">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-7">
                    <div class="section-title position-relative pb-3 mb-5">
                        <h5 class="fw-bold text-primary text-uppercase">Nous contacter</h5>
                        <h1 class="mb-0">Besoins de plus d'informations, Voulez poser une question,nous laisser un message?</h1>
                    </div>
                    <div class="row gx-3">
                        <div class="col-sm-6 wow zoomIn" data-wow-delay="0.2s">
                            <h5 class="mb-4"><i class="fa fa-reply text-primary me-3"></i>Nous repondons en 24h</h5>
                        </div>
                        <div class="col-sm-6 wow zoomIn" data-wow-delay="0.4s">
                            <h5 class="mb-4"><i class="fa fa-phone-alt text-primary me-3"></i>Nos numeros de téléphones sont ouverts pour vous 24h/24</h5>
                        </div>
                    </div>
                    <div class="row gx-3">

                        <div class="col-sm-6 d-flex align-items-center mt-2 wow zoomIn" data-wow-delay="0.6s">
                            <div class="bg-primary d-flex align-items-center justify-content-center rounded" style="width: 60px; height: 60px;">
                                <i class="fa fa-phone-alt text-white"></i>
                            </div>
                            <div class="ps-4">
                                <h5 class="mb-2">Nous appeller</h5>
                                <h4 class="text-primary mb-0">+224 000 000 000</h4>
                            </div>
                        </div>
                        <div class="col-sm-6 d-flex align-items-center mt-2 wow zoomIn" data-wow-delay="0.6s">
                            <div class="bg-primary d-flex align-items-center justify-content-center rounded" style="width: 60px; height: 60px;">
                                <i class="fa fa-phone-alt text-white"></i>
                            </div>
                            <div class="ps-4">
                                <h5 class="mb-2">Nous appeller</h5>
                                <h4 class="text-primary mb-0">+224 000 000 000</h4>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="col-lg-5">
                    <div class="bg-primary rounded h-100 d-flex align-items-center p-5 wow zoomIn" data-wow-delay="0.9s">
                        <form>
                            <div class="row g-3">
                                <div class="col-xl-12">
                                    <input type="text" class="form-control bg-light border-0" placeholder="Votre nom complet" style="height: 55px;">
                                </div>
                                <div class="col-12">
                                    <input type="email" class="form-control bg-light border-0" placeholder="Votre email" style="height: 55px;">
                                </div>
                                <div class="col-12">
                                    <select class="form-select bg-light border-0" style="height: 55px;">
                                        <option value="2">Demande d'info</option>
                                        <option value="1">Question l'utilisation</option>
                                        <option value="3">j'ai un problème</option>
                                        <option value="4">Autre</option>
                                    </select>
                                </div>
                                <div class="col-12">
                                    <textarea class="form-control bg-light border-0" rows="3" placeholder="Message"></textarea>
                                </div>
                                <div class="col-12">
                                    <button class="btn btn-dark w-100 py-3" type="submit">Envoyer</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

templates/entreprise/_partials/_formSoumettre.html.twig
<div class="container-fluid  wow fadeInUp" data-wow-delay="0.1s" id="contact">
    <div class="container" style="width:50%; margin-top:5%">
        <div class="bg-primary rounded h-100 d-flex justify-content-center align-items-center p-5 wow zoomIn" data-wow-delay="0.9s">
            <form action="{{ path('app_soumettre') }}" method="POST" id="multiStepForm">
                <div class="row g-3" id="step1">
                    <h2 style="text-align:center;">Vos Informations</h2>
                    <div class="col-xl-12">
                        <label for="nom" class="form-label text-light">Votre nom</label>
                        <input type="text" name="nom" id="nom" class="form-control bg-light border-0"
                            placeholder="Ex: DIALLO" style="height: 55px;">
                    </div>
                    <div class="col-12">
                        <label for="prenom" class="form-label text-light">Votre prénom</label>
                        <input type="text" name="prenom" id="prenom" class="form-control bg-light border-0"
                            placeholder="Ex: Mika" required style="height: 55px;">
                    </div>
                    <div class="col-12">
                        <label for="poste" class="form-label text-light">Poste Occupé</label>
                        <input type="text" name="poste" id="poste" class="form-control bg-light border-0"
                            placeholder="Ex: Comptable" required style="height: 55px;">
                    </div>
                    <div class="col-12">
                        <label for="mail" class="form-label text-light">Adresse E-mail</label>
                        <input type="email" name="mail" id="mail" class="form-control bg-light border-0"
                            placeholder="Ex: mika@gmail.com" required style="height: 55px;">
                    </div>
                    <div class="col-12">
                        <label for="tel" class="form-label text-light">Numéro de Téléphone</label>
                        <input type="text" name="tel" id="tel" class="form-control bg-light border-0"
                            placeholder="Ex: +224 625 235 760 " required style="height: 55px;">
                    </div>
                    <div class="col-12 d-flex justify-content-end align-items-end">
                        <button type="button" class="btn btn-dark" onclick="nextStep()">Suivant</button>
                    </div>
                </div>
                <div class="row g-3 d-none" id="step2">
                    <h2 style="text-align:center;">Renseignement sur l'Entreprise</h2>
                    <div class="col-12">
                        <label for="nomEntreprise" class="form-label text-light">Votre nom d'Entreprise</label>
                        <input type="text" name="nomEntreprise" id="nomEntreprise"
                            class="form-control bg-light border-0" placeholder="Ex: CANAL +" required style="height: 55px;">
                    </div>
                    <div class="col-xl-12">
                        <label for="email" class="form-label text-light">Adresse E-mail</label>
                        <input type="email" name="email" id="email" class="form-control bg-light border-0"
                            placeholder="Ex:diallo.mikat@example.com" style="height: 55px;">
                    </div>
                    <div class="col-xl-12">
                        <label for="telephone" class="form-label text-light">Numéro de Téléphone</label>
                        <input type="text" name="telephone" id="telephone" class="form-control bg-light border-0"
                            placeholder="Ex: +224 625 235 760" required style="height: 55px;">
                    </div>
                    <div class="col-12">
                        <label for="taille" class="form-label text-light">Taille de l'Entreprise</label>
                        <select name="taille" id="taille" class="form-select bg-light border-0" style="height: 55px;">
                            <option value="Petite Entreprise">Petite entreprise</option>
                            <option value="Moyenne Entreprise">Moyenne entreprise</option>
                            <option value="Grande Entreprise">Grande entreprise</option>
                        </select>
                    </div>
                    <div class="col-12">
                        <label for="secteur" class="form-label text-light">Domaine d'Activité</label>
                        <input type="text" name="secteur" id="secteur" class="form-control bg-light border-0"
                            placeholder="Ex: Technologie"  required style="height: 55px;">
                    </div>
                    <div class="col-xl-12">
                        <label for="lieu" class="form-label text-light">Lieu</label>
                        <input type="text" name="lieu" id="lieu" class="form-control bg-light border-0"
                            placeholder="Ex: Route Niger, Matam, Conakry" required style="height: 55px;">
                    </div>
                    <div class="col-12">
                        <div class="row">
                            <div class="col-md-6">
                                <button type="button" class="btn btn-dark w-100 py-3"
                                    onclick="prevStep()">Précédent</button>
                            </div>
                            <div class="col-md-6">
                                <button type="button" class="btn btn-dark w-100 py-3"
                                    onclick="nextStep()">Suivant</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row g-3 d-none" id="step3">
                    <h2 style="text-align:center;">Détails de l'offre</h2>
                    <div class="col-12">
                        <label for="typeOffre" class="form-label text-light">Type d'Offre</label>
                        <select name="typeOffre" id="typeOffre" class="form-select bg-light border-0"
                            style="height: 55px;">
                            {% for offre in typeOffres %}
                            <option value="{{ offre.id }}">{{ offre.nom }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-12">
                        <label for="description" class="form-label text-light">Description de l'Offre</label>
                        <textarea name="description" id="description" class="form-control bg-light border-0" rows="6"
                            placeholder="Ex: Nous recherchons un développeur expérimenté..." required></textarea>
                    </div>
                    <div class="col-12">
                        <label for="dateDepot" class="form-label text-light">Date Dépôt</label>
                        <input type="date" name="dateDepot" id="dateDepot" class="form-control bg-light border-0"
                            required style="height: 55px;">
                    </div>
                    <div class="col-12">
                        <label for="dateCloture" class="form-label text-light">Date limite</label>
                        <input type="date" name="dateCloture" id="dateCloture" class="form-control bg-light border-0"
                            required style="height: 55px;">
                    </div>
                    <div class="col-12">
                        <div class="row">
                            <div class="col-md-6">
                                <button type="button" class="btn btn-dark w-100 py-3"
                                    onclick="prevStep()">Précédent</button>
                            </div>
                            <div class="col-md-6">
                                <button type="button" class="btn btn-dark w-100 py-3"
                                    onclick="nextStep()">Suivant</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row g-3 d-none" id="step4">
                    <h2 style="text-align:center;">Profil Recherché</h2>
                    <div class="col-12">
                        <label for="experience" class="form-label text-light">Expérience Demandée</label>
                        <input type="text" name="experience" id="experience" class="form-control bg-light border-0"
                            placeholder="Ex: 5 ans dans un poste similaire" required style="height: 55px;">
                    </div>
                    <div class="col-12">
                        <label for="competence" class="form-label text-light">Compétence Demandée</label>
                        <input type="text" name="competence" id="competence" class="form-control bg-light border-0"
                            placeholder="Ex: Maîtrise de JavaScript, Python" required style="height: 55px;">
                    </div>
                    <div class="col-12">
                        <label for="niveau" class="form-label text-light">Niveau</label>
                        <input type="text" name="niveau" id="niveau" class="form-control bg-light border-0"
                            placeholder="Ex: Licence 2" style="height: 55px;" required>
                    </div>
                    <div class="col-12">
                        <label for="domaine" class="form-label text-light">Domaine</label>
                        <input type="text" name="domaine" id="domaine" class="form-control bg-light border-0"
                            placeholder="Ex: Informatique, Biomedicale,..." required style="height: 55px;">
                    </div>
                    <div class="col-12">
                        <div class="row">
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-dark py-3">Soumettre l'Offre</button>
                            </div>
                            <div class="col-md-6">
                                <button type="button" class="btn btn-dark py-3" onclick="prevStep()">Précédent</button>
                            </div>
                        </div>
                        <div class="col-12"></div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    let currentStep = 1;

    function showStep(step) {
        document.querySelectorAll('.row.g-3').forEach((el, index) => {
            if (index + 1 === step) {
                el.classList.remove('d-none');
            } else {
                el.classList.add('d-none');
            }
        });
    }

    function nextStep() {
        let isValid = validateForm(currentStep);
        if (isValid && currentStep < 4) {
            currentStep++;
            showStep(currentStep);
        }
    }

    function prevStep() {
        if (currentStep > 1) {
            currentStep--;
            showStep(currentStep);
        }
    }

    function validateForm(step) {
        let inputs = document.querySelectorAll(`#step${step} input[required], #step${step} select[required], #step${step} textarea[required]`);
        let isValid = true;
        inputs.forEach(input => {
            if (!input.value.trim()) {
                isValid = false;
                input.classList.add('is-invalid');
            } else {
                input.classList.remove('is-invalid');
            }
        });
        return isValid;
    }

    // Initialize the first step
    showStep(currentStep);
</script>

templates/entreprise/_partials/_offre.html.twig
{% for offre in offre_publies %}
			<div
				class="col-lg-6">
				<!-- Dropdown Card Example -->
				<div
					class="card shadow mb-4">
					<!-- Card Header - Dropdown -->
					<div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
						<h6 class="m-0 font-weight-bold text-success">Publié</h6>
						<h6 class="m-0 font-weight-bold text-primary">{{offre.nomEntreprise}}</h6>
						<div class="dropdown no-arrow">
							<a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
							</a>
							<div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
								<div class="dropdown-header">Actions:</div>
								<a class="dropdown-item bg-success text-white" href="{{path('app_showEntreprise', {'id': offre.id})}}">Voir</a>
								<a class="dropdown-item bg-info text-white" href="#">Modifier</a>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item bg-warning text-white" href="#">Autre</a>
								<a class="dropdown-item bg-danger text-white" href="{{path('app_offre_delete', {'id': offre.id})}}">Supprimer</a>
							</div>
						</div>
					</div>
					<!-- Card Body -->
					<div class="card-body">
						<div>
							<strong class="text-center">
								{% for offres in offre.fkTypeOffre %}
									{{ offres.nom }}<br>
								{% endfor %}
							</strong>
							<p>
								{{ offre.description }}<br>
								Domaine d'activité :
								<strong>{{offre.nomOffre}}</strong>
							</p>
							<p>
								Date début :
								<strong>{{offre.dateDebut|date('d F Y') }}</strong><br>
								Date Limite :
								<strong>{{offre.dateLimite|date('d F Y') }}</strong>
							</p>
						</div>
					</div>
				</div>
			</div>
		{% endfor %}

templates/entreprise/_partials/_offreEntreprise.html.twig
{% for offre in offre_entreprises %}
			<div
				class="col-lg-6">
				<!-- Dropdown Card Example -->
				<div
					class="card shadow mb-4">
					<!-- Card Header - Dropdown -->
					<div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">

						{% if offre.statut %}
							<h6 class="m-0 font-weight-bold text-success">Publié</h6>
							{% else %}
							<h6 class="m-0 font-weight-bold text-danger">Non Publié</h6>
						{% endif %}
					<h6 class="m-0 font-weight-bold text-primary">{{offre.nomEntreprise}}</h6>
						<div class="dropdown no-arrow">
							<a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
							</a>
							<div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
								<div class="dropdown-header">Actions:</div>
								<a class="dropdown-item bg-success text-white" href="{{path('app_showEntreprise', {'id': offre.id})}}">Voir</a>
								<a class="dropdown-item bg-info text-white" href="{{path('app_publier', {'id': offre.id})}}">Publier</a>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item bg-warning text-white" href="#">Autre</a>
								<a class="dropdown-item bg-danger text-white" href="#">Supprimer</a>
							</div>
						</div>
					</div>
					<!-- Card Body -->
					<div class="card-body">
						<div>
							<strong class="text-center">
								{% for offres in offre.fkTypeOffre %}
									{{ offres.nom }}<br>
								{% endfor %}
							</strong>
							<p>
								{{ offre.description }}<br>
								Domaine d'activité :
								<strong>{{offre.domaine}}</strong>
							</p>
							<p>
								Date début :
								<strong>{{offre.dateCreation|date('d F Y') }}</strong><br>
								Date Limite :
								<strong>{{offre.dateLimite|date('d F Y') }}</strong>
							</p>
						</div>
					</div>
				</div>
			</div>
		{% endfor %}